imports:
  - { resource: '/app/src/Modules/Games/Infrastructure/games_mongodb.yaml' }

doctrine_mongodb:
  connections:
    default:
      server: '%env(MONGODB_URL)%'
      options: {}
  default_database: '%env(MONGODB_DB)%'
  document_managers:
    default:
      auto_mapping: true